steps:
  - name: node:20-bullseye
    entrypoint: bash
    args:
      - -lc
      - corepack enable && pnpm dlx prisma@5.22.0 migrate deploy --schema=apps/api/prisma/schema.prisma
    secretEnv:
      - DATABASE_URL
      - DATABASE_DIRECT_URL
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/api/Dockerfile
      - -t
      - gcr.io/$PROJECT_ID/health-agent-api:$BUILD_ID
      - -t
      - gcr.io/$PROJECT_ID/health-agent-api:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/health-agent-api:$BUILD_ID
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/$PROJECT_ID/health-agent-api:latest
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --image
      - gcr.io/$PROJECT_ID/health-agent-api:$BUILD_ID
      - --region
      - $_REGION
      - --platform
      - managed
      - --set-secrets
      - DATABASE_URL=${_DATABASE_URL_SECRET}:latest
      - --set-secrets
      - DATABASE_DIRECT_URL=${_DATABASE_DIRECT_URL_SECRET}:latest
      - --set-secrets
      - TINKER_API_KEY=${_TINKER_API_KEY_SECRET}:latest
      - --quiet
images:
  - gcr.io/$PROJECT_ID/health-agent-api:$BUILD_ID
  - gcr.io/$PROJECT_ID/health-agent-api:latest
substitutions:
  _SERVICE: health-agent-api
  _REGION: australia-southeast1
  _TINKER_API_KEY_SECRET: tinker-api-key
  _DATABASE_URL_SECRET: health-agent-database-url
  _DATABASE_DIRECT_URL_SECRET: health-agent-database-direct-url
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/${_DATABASE_URL_SECRET}/versions/latest
      env: DATABASE_URL
    - versionName: projects/$PROJECT_ID/secrets/${_DATABASE_DIRECT_URL_SECRET}/versions/latest
      env: DATABASE_DIRECT_URL
